# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Article Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Article Description')),
                ('price', models.IntegerField(default=0, verbose_name='Article Price')),
                ('total_in_shelf', models.IntegerField(default=0, verbose_name='Total Articles in Shelf')),
                ('total_in_vault', models.IntegerField(default=0, verbose_name='Total Articles in Vault')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Store Name')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Store Address')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_store', to='supershoes.Stores', verbose_name='Store'),
        ),
    ]
